// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertReviewLog = `-- name: InsertReviewLog :exec
INSERT INTO review_logs (user_id, mistake_id, action)
VALUES ($1, $2, $3)
`

type InsertReviewLogParams struct {
	UserID    string `json:"user_id"`
	MistakeID string `json:"mistake_id"`
	Action    string `json:"action"`
}

func (q *Queries) InsertReviewLog(ctx context.Context, arg InsertReviewLogParams) error {
	_, err := q.db.Exec(ctx, insertReviewLog, arg.UserID, arg.MistakeID, arg.Action)
	return err
}

const reviewLogsSince = `-- name: ReviewLogsSince :many
SELECT created_at FROM review_logs
WHERE user_id = $1 AND created_at >= $2::timestamptz
ORDER BY created_at DESC
LIMIT 2000
`

type ReviewLogsSinceParams struct {
	UserID string             `json:"user_id"`
	Since  pgtype.Timestamptz `json:"since"`
}

func (q *Queries) ReviewLogsSince(ctx context.Context, arg ReviewLogsSinceParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, reviewLogsSince, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Timestamptz{}
	for rows.Next() {
		var created_at pgtype.Timestamptz
		if err := rows.Scan(&created_at); err != nil {
			return nil, err
		}
		items = append(items, created_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
