// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mistakes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPool = `-- name: CountPool :one
SELECT count(*) FROM mistakes
WHERE user_id = $1
  AND ($2::text = '' OR subject = $2::text)
  AND ($3::text = 'all' OR mastery = $3::text)
`

type CountPoolParams struct {
	UserID  string `json:"user_id"`
	Subject string `json:"subject"`
	Mastery string `json:"mastery"`
}

func (q *Queries) CountPool(ctx context.Context, arg CountPoolParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPool, arg.UserID, arg.Subject, arg.Mastery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMistake = `-- name: CreateMistake :one
INSERT INTO mistakes (
    user_id, image_file_id, subject, knowledge_points, question_type,
    difficulty, ocr_text, answer, error_reason, mastery, wrong_count,
    kind, from_mistake_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, user_id, image_file_id, subject, knowledge_points, question_type, difficulty, ocr_text, answer, error_reason, mastery, wrong_count, kind, from_mistake_id, created_at, last_review_at
`

type CreateMistakeParams struct {
	UserID          string   `json:"user_id"`
	ImageFileID     string   `json:"image_file_id"`
	Subject         string   `json:"subject"`
	KnowledgePoints []string `json:"knowledge_points"`
	QuestionType    string   `json:"question_type"`
	Difficulty      string   `json:"difficulty"`
	OcrText         string   `json:"ocr_text"`
	Answer          string   `json:"answer"`
	ErrorReason     string   `json:"error_reason"`
	Mastery         string   `json:"mastery"`
	WrongCount      int32    `json:"wrong_count"`
	Kind            string   `json:"kind"`
	FromMistakeID   string   `json:"from_mistake_id"`
}

func (q *Queries) CreateMistake(ctx context.Context, arg CreateMistakeParams) (Mistake, error) {
	row := q.db.QueryRow(ctx, createMistake,
		arg.UserID,
		arg.ImageFileID,
		arg.Subject,
		arg.KnowledgePoints,
		arg.QuestionType,
		arg.Difficulty,
		arg.OcrText,
		arg.Answer,
		arg.ErrorReason,
		arg.Mastery,
		arg.WrongCount,
		arg.Kind,
		arg.FromMistakeID,
	)
	var i Mistake
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ImageFileID,
		&i.Subject,
		&i.KnowledgePoints,
		&i.QuestionType,
		&i.Difficulty,
		&i.OcrText,
		&i.Answer,
		&i.ErrorReason,
		&i.Mastery,
		&i.WrongCount,
		&i.Kind,
		&i.FromMistakeID,
		&i.CreatedAt,
		&i.LastReviewAt,
	)
	return i, err
}

const deleteMistake = `-- name: DeleteMistake :one
DELETE FROM mistakes
WHERE id = $2::uuid AND user_id = $1
RETURNING image_file_id
`

type DeleteMistakeParams struct {
	UserID string      `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteMistake(ctx context.Context, arg DeleteMistakeParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteMistake, arg.UserID, arg.ID)
	var image_file_id string
	err := row.Scan(&image_file_id)
	return image_file_id, err
}

const exportMistakes = `-- name: ExportMistakes :many
SELECT id, user_id, image_file_id, subject, knowledge_points, question_type, difficulty, ocr_text, answer, error_reason, mastery, wrong_count, kind, from_mistake_id, created_at, last_review_at FROM mistakes
WHERE user_id = $1
  AND (
    (cardinality($2::text[]) > 0 AND id::text = ANY($2::text[]))
    OR
    (cardinality($2::text[]) = 0 AND ($3::text = '' OR subject = $3::text))
  )
ORDER BY created_at DESC
LIMIT 200
`

type ExportMistakesParams struct {
	UserID  string   `json:"user_id"`
	Ids     []string `json:"ids"`
	Subject string   `json:"subject"`
}

func (q *Queries) ExportMistakes(ctx context.Context, arg ExportMistakesParams) ([]Mistake, error) {
	rows, err := q.db.Query(ctx, exportMistakes, arg.UserID, arg.Ids, arg.Subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mistake{}
	for rows.Next() {
		var i Mistake
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ImageFileID,
			&i.Subject,
			&i.KnowledgePoints,
			&i.QuestionType,
			&i.Difficulty,
			&i.OcrText,
			&i.Answer,
			&i.ErrorReason,
			&i.Mastery,
			&i.WrongCount,
			&i.Kind,
			&i.FromMistakeID,
			&i.CreatedAt,
			&i.LastReviewAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMistake = `-- name: GetMistake :one
SELECT id, user_id, image_file_id, subject, knowledge_points, question_type, difficulty, ocr_text, answer, error_reason, mastery, wrong_count, kind, from_mistake_id, created_at, last_review_at FROM mistakes
WHERE id = $2::uuid AND user_id = $1
`

type GetMistakeParams struct {
	UserID string      `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) GetMistake(ctx context.Context, arg GetMistakeParams) (Mistake, error) {
	row := q.db.QueryRow(ctx, getMistake, arg.UserID, arg.ID)
	var i Mistake
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ImageFileID,
		&i.Subject,
		&i.KnowledgePoints,
		&i.QuestionType,
		&i.Difficulty,
		&i.OcrText,
		&i.Answer,
		&i.ErrorReason,
		&i.Mastery,
		&i.WrongCount,
		&i.Kind,
		&i.FromMistakeID,
		&i.CreatedAt,
		&i.LastReviewAt,
	)
	return i, err
}

const gradeMistake = `-- name: GradeMistake :one
UPDATE mistakes
SET mastery = $2::text,
    wrong_count = wrong_count + $3::int,
    last_review_at = now()
WHERE id = $4::uuid AND user_id = $1
RETURNING id, user_id, image_file_id, subject, knowledge_points, question_type, difficulty, ocr_text, answer, error_reason, mastery, wrong_count, kind, from_mistake_id, created_at, last_review_at
`

type GradeMistakeParams struct {
	UserID   string      `json:"user_id"`
	Mastery  string      `json:"mastery"`
	WrongInc int32       `json:"wrong_inc"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GradeMistake(ctx context.Context, arg GradeMistakeParams) (Mistake, error) {
	row := q.db.QueryRow(ctx, gradeMistake,
		arg.UserID,
		arg.Mastery,
		arg.WrongInc,
		arg.ID,
	)
	var i Mistake
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ImageFileID,
		&i.Subject,
		&i.KnowledgePoints,
		&i.QuestionType,
		&i.Difficulty,
		&i.OcrText,
		&i.Answer,
		&i.ErrorReason,
		&i.Mastery,
		&i.WrongCount,
		&i.Kind,
		&i.FromMistakeID,
		&i.CreatedAt,
		&i.LastReviewAt,
	)
	return i, err
}

const listMistakes = `-- name: ListMistakes :many
SELECT id, user_id, image_file_id, subject, knowledge_points, question_type, difficulty, ocr_text, answer, error_reason, mastery, wrong_count, kind, from_mistake_id, created_at, last_review_at FROM mistakes
WHERE user_id = $1
  AND ($2::text = '' OR subject = $2::text)
ORDER BY created_at DESC
LIMIT $3::int
`

type ListMistakesParams struct {
	UserID  string `json:"user_id"`
	Subject string `json:"subject"`
	Lim     int32  `json:"lim"`
}

func (q *Queries) ListMistakes(ctx context.Context, arg ListMistakesParams) ([]Mistake, error) {
	rows, err := q.db.Query(ctx, listMistakes, arg.UserID, arg.Subject, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mistake{}
	for rows.Next() {
		var i Mistake
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ImageFileID,
			&i.Subject,
			&i.KnowledgePoints,
			&i.QuestionType,
			&i.Difficulty,
			&i.OcrText,
			&i.Answer,
			&i.ErrorReason,
			&i.Mastery,
			&i.WrongCount,
			&i.Kind,
			&i.FromMistakeID,
			&i.CreatedAt,
			&i.LastReviewAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randomMistake = `-- name: RandomMistake :one
SELECT id, user_id, image_file_id, subject, knowledge_points, question_type, difficulty, ocr_text, answer, error_reason, mastery, wrong_count, kind, from_mistake_id, created_at, last_review_at FROM mistakes
WHERE user_id = $1
  AND ($2::text = '' OR subject = $2::text)
  AND ($3::text = 'all' OR mastery = $3::text)
ORDER BY random()
LIMIT 1
`

type RandomMistakeParams struct {
	UserID  string `json:"user_id"`
	Subject string `json:"subject"`
	Mastery string `json:"mastery"`
}

func (q *Queries) RandomMistake(ctx context.Context, arg RandomMistakeParams) (Mistake, error) {
	row := q.db.QueryRow(ctx, randomMistake, arg.UserID, arg.Subject, arg.Mastery)
	var i Mistake
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ImageFileID,
		&i.Subject,
		&i.KnowledgePoints,
		&i.QuestionType,
		&i.Difficulty,
		&i.OcrText,
		&i.Answer,
		&i.ErrorReason,
		&i.Mastery,
		&i.WrongCount,
		&i.Kind,
		&i.FromMistakeID,
		&i.CreatedAt,
		&i.LastReviewAt,
	)
	return i, err
}

const statsBySubject = `-- name: StatsBySubject :many
SELECT subject, count(*)::int AS count
FROM mistakes
WHERE user_id = $1
GROUP BY subject
ORDER BY count DESC
`

type StatsBySubjectRow struct {
	Subject string `json:"subject"`
	Count   int32  `json:"count"`
}

func (q *Queries) StatsBySubject(ctx context.Context, userID string) ([]StatsBySubjectRow, error) {
	rows, err := q.db.Query(ctx, statsBySubject, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsBySubjectRow{}
	for rows.Next() {
		var i StatsBySubjectRow
		if err := rows.Scan(&i.Subject, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsCounts = `-- name: StatsCounts :one
SELECT
    count(*)::int AS total,
    count(*) FILTER (WHERE mastery = 'mastered')::int AS mastered,
    count(*) FILTER (WHERE mastery = 'reviewing')::int AS reviewing
FROM mistakes
WHERE user_id = $1
`

type StatsCountsRow struct {
	Total     int32 `json:"total"`
	Mastered  int32 `json:"mastered"`
	Reviewing int32 `json:"reviewing"`
}

func (q *Queries) StatsCounts(ctx context.Context, userID string) (StatsCountsRow, error) {
	row := q.db.QueryRow(ctx, statsCounts, userID)
	var i StatsCountsRow
	err := row.Scan(&i.Total, &i.Mastered, &i.Reviewing)
	return i, err
}

const updateMastery = `-- name: UpdateMastery :one
UPDATE mistakes
SET mastery = $2::text
WHERE id = $3::uuid AND user_id = $1
RETURNING id, user_id, image_file_id, subject, knowledge_points, question_type, difficulty, ocr_text, answer, error_reason, mastery, wrong_count, kind, from_mistake_id, created_at, last_review_at
`

type UpdateMasteryParams struct {
	UserID  string      `json:"user_id"`
	Mastery string      `json:"mastery"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateMastery(ctx context.Context, arg UpdateMasteryParams) (Mistake, error) {
	row := q.db.QueryRow(ctx, updateMastery, arg.UserID, arg.Mastery, arg.ID)
	var i Mistake
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ImageFileID,
		&i.Subject,
		&i.KnowledgePoints,
		&i.QuestionType,
		&i.Difficulty,
		&i.OcrText,
		&i.Answer,
		&i.ErrorReason,
		&i.Mastery,
		&i.WrongCount,
		&i.Kind,
		&i.FromMistakeID,
		&i.CreatedAt,
		&i.LastReviewAt,
	)
	return i, err
}
