// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Mistake struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          string             `json:"user_id"`
	ImageFileID     string             `json:"image_file_id"`
	Subject         string             `json:"subject"`
	KnowledgePoints []string           `json:"knowledge_points"`
	QuestionType    string             `json:"question_type"`
	Difficulty      string             `json:"difficulty"`
	OcrText         string             `json:"ocr_text"`
	Answer          string             `json:"answer"`
	ErrorReason     string             `json:"error_reason"`
	Mastery         string             `json:"mastery"`
	WrongCount      int32              `json:"wrong_count"`
	Kind            string             `json:"kind"`
	FromMistakeID   string             `json:"from_mistake_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastReviewAt    pgtype.Timestamptz `json:"last_review_at"`
}

type ReviewLog struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	MistakeID string             `json:"mistake_id"`
	Action    string             `json:"action"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          string             `json:"id"`
	Role        string             `json:"role"`
	NickName    string             `json:"nick_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}
