// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recognitions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimRecognitionJob = `-- name: ClaimRecognitionJob :one
UPDATE recognition_jobs
SET status = 'processing',
    attempts = GREATEST(attempts, $2),
    last_error = '',
    updated_at = now()
WHERE id = $1
  AND user_id = $3
  AND (
    status IN ('queued', 'retrying', 'dead_lettered', 'publish_failed')
    OR (status = 'processing' AND updated_at < now() - interval '90 seconds')
  )
RETURNING id, request_id, event_id, user_id, image_file_id, status, attempts, result, last_error, published_at, completed_at, created_at, updated_at
`

type ClaimRecognitionJobParams struct {
	ID       pgtype.UUID `json:"id"`
	Attempts int32       `json:"attempts"`
	UserID   string      `json:"user_id"`
}

func (q *Queries) ClaimRecognitionJob(ctx context.Context, arg ClaimRecognitionJobParams) (RecognitionJob, error) {
	row := q.db.QueryRow(ctx, claimRecognitionJob, arg.ID, arg.Attempts, arg.UserID)
	var i RecognitionJob
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.EventID,
		&i.UserID,
		&i.ImageFileID,
		&i.Status,
		&i.Attempts,
		&i.Result,
		&i.LastError,
		&i.PublishedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeRecognitionJob = `-- name: CompleteRecognitionJob :one
UPDATE recognition_jobs
SET status = 'succeeded',
    result = $2::jsonb,
    last_error = '',
    completed_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, request_id, event_id, user_id, image_file_id, status, attempts, result, last_error, published_at, completed_at, created_at, updated_at
`

type CompleteRecognitionJobParams struct {
	ID     pgtype.UUID `json:"id"`
	Result []byte      `json:"result"`
}

func (q *Queries) CompleteRecognitionJob(ctx context.Context, arg CompleteRecognitionJobParams) (RecognitionJob, error) {
	row := q.db.QueryRow(ctx, completeRecognitionJob, arg.ID, arg.Result)
	var i RecognitionJob
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.EventID,
		&i.UserID,
		&i.ImageFileID,
		&i.Status,
		&i.Attempts,
		&i.Result,
		&i.LastError,
		&i.PublishedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecognitionJob = `-- name: CreateRecognitionJob :one
INSERT INTO recognition_jobs (request_id, event_id, user_id, image_file_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (request_id) DO UPDATE
SET request_id = EXCLUDED.request_id
RETURNING id, request_id, event_id, user_id, image_file_id, status, attempts, result, last_error, published_at, completed_at, created_at, updated_at
`

type CreateRecognitionJobParams struct {
	RequestID   string      `json:"request_id"`
	EventID     pgtype.UUID `json:"event_id"`
	UserID      string      `json:"user_id"`
	ImageFileID string      `json:"image_file_id"`
}

func (q *Queries) CreateRecognitionJob(ctx context.Context, arg CreateRecognitionJobParams) (RecognitionJob, error) {
	row := q.db.QueryRow(ctx, createRecognitionJob,
		arg.RequestID,
		arg.EventID,
		arg.UserID,
		arg.ImageFileID,
	)
	var i RecognitionJob
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.EventID,
		&i.UserID,
		&i.ImageFileID,
		&i.Status,
		&i.Attempts,
		&i.Result,
		&i.LastError,
		&i.PublishedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecognitionJob = `-- name: GetRecognitionJob :one
SELECT id, request_id, event_id, user_id, image_file_id, status, attempts, result, last_error, published_at, completed_at, created_at, updated_at FROM recognition_jobs
WHERE id = $1 AND user_id = $2
`

type GetRecognitionJobParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetRecognitionJob(ctx context.Context, arg GetRecognitionJobParams) (RecognitionJob, error) {
	row := q.db.QueryRow(ctx, getRecognitionJob, arg.ID, arg.UserID)
	var i RecognitionJob
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.EventID,
		&i.UserID,
		&i.ImageFileID,
		&i.Status,
		&i.Attempts,
		&i.Result,
		&i.LastError,
		&i.PublishedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRecognitionJobError = `-- name: MarkRecognitionJobError :one
UPDATE recognition_jobs
SET status = $2,
    attempts = GREATEST(attempts, $3),
    last_error = $4,
    completed_at = CASE WHEN $2 IN ('failed', 'dead_lettered') THEN now() ELSE NULL END,
    updated_at = now()
WHERE id = $1
RETURNING id, request_id, event_id, user_id, image_file_id, status, attempts, result, last_error, published_at, completed_at, created_at, updated_at
`

type MarkRecognitionJobErrorParams struct {
	ID        pgtype.UUID `json:"id"`
	Status    string      `json:"status"`
	Attempts  int32       `json:"attempts"`
	LastError string      `json:"last_error"`
}

func (q *Queries) MarkRecognitionJobError(ctx context.Context, arg MarkRecognitionJobErrorParams) (RecognitionJob, error) {
	row := q.db.QueryRow(ctx, markRecognitionJobError,
		arg.ID,
		arg.Status,
		arg.Attempts,
		arg.LastError,
	)
	var i RecognitionJob
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.EventID,
		&i.UserID,
		&i.ImageFileID,
		&i.Status,
		&i.Attempts,
		&i.Result,
		&i.LastError,
		&i.PublishedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRecognitionJobPublishFailed = `-- name: MarkRecognitionJobPublishFailed :exec
UPDATE recognition_jobs
SET status = 'publish_failed', last_error = $2, updated_at = now()
WHERE id = $1 AND published_at IS NULL
`

type MarkRecognitionJobPublishFailedParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError string      `json:"last_error"`
}

func (q *Queries) MarkRecognitionJobPublishFailed(ctx context.Context, arg MarkRecognitionJobPublishFailedParams) error {
	_, err := q.db.Exec(ctx, markRecognitionJobPublishFailed, arg.ID, arg.LastError)
	return err
}

const markRecognitionJobPublished = `-- name: MarkRecognitionJobPublished :exec
UPDATE recognition_jobs
SET status = 'queued', published_at = now(), last_error = '', updated_at = now()
WHERE id = $1 AND status IN ('queued', 'publish_failed')
`

func (q *Queries) MarkRecognitionJobPublished(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markRecognitionJobPublished, id)
	return err
}
