// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const adminPerUser = `-- name: AdminPerUser :many
SELECT
    user_id,
    count(*)::int AS count,
    count(*) FILTER (WHERE mastery = 'mastered')::int AS mastered
FROM mistakes
GROUP BY user_id
ORDER BY count DESC
LIMIT 50
`

type AdminPerUserRow struct {
	UserID   string `json:"user_id"`
	Count    int32  `json:"count"`
	Mastered int32  `json:"mastered"`
}

func (q *Queries) AdminPerUser(ctx context.Context) ([]AdminPerUserRow, error) {
	rows, err := q.db.Query(ctx, adminPerUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminPerUserRow{}
	for rows.Next() {
		var i AdminPerUserRow
		if err := rows.Scan(&i.UserID, &i.Count, &i.Mastered); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAllMastered = `-- name: CountAllMastered :one
SELECT count(*)::int FROM mistakes WHERE mastery = 'mastered'
`

func (q *Queries) CountAllMastered(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countAllMastered)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countAllMistakes = `-- name: CountAllMistakes :one
SELECT count(*)::int FROM mistakes
`

func (q *Queries) CountAllMistakes(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countAllMistakes)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*)::int FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const ensureUser = `-- name: EnsureUser :one
INSERT INTO users (id, role, nick_name, last_login_at)
VALUES ($1, 'user', $2::text, now())
ON CONFLICT (id) DO UPDATE SET last_login_at = now()
RETURNING id, role, nick_name, created_at, last_login_at
`

type EnsureUserParams struct {
	ID       string `json:"id"`
	NickName string `json:"nick_name"`
}

func (q *Queries) EnsureUser(ctx context.Context, arg EnsureUserParams) (User, error) {
	row := q.db.QueryRow(ctx, ensureUser, arg.ID, arg.NickName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.NickName,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, role, nick_name, created_at, last_login_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.NickName,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
